name: generate animation

on:
  # roda automaticamente a cada 24h
  schedule:
    - cron: "0 */24 * * *" 
  
  # permite rodar manualmente
  workflow_dispatch:
  
  # roda a cada push na branch master
  push:
    branches:
      - main
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # gera a cobrinha com base no perfil
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: gabrielkauee
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # envia o conteúdo da pasta dist para a branch output
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
