name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "59 23 * * *"

# dá permissão de escrita pro GITHUB_TOKEN (necessário pra criar o branch output)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: gabrielkauee
          outputs: dist/snake.svg dist/snake-dark.svg

      # passo de debug pra garantir que os arquivos foram criados
      - name: Debug – show generated files
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "dist content:"
          ls -la dist

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
